"""add is_suspended to users and default is_active false

Revision ID: 37dfc5427851
Revises: 6d06483a3c2c
Create Date: 2025-09-23 03:45:01.496880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37dfc5427851'
down_revision: Union[str, Sequence[str], None] = '6d06483a3c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_suspended')
    # ### end Alembic commands ###
