"""added senio to cands

Revision ID: 3f9ededb9c2d
Revises: dd5de4337320
Create Date: 2025-09-28 22:50:58.777937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f9ededb9c2d'
down_revision: Union[str, Sequence[str], None] = 'dd5de4337320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('seniority', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'seniority')
    # ### end Alembic commands ###
