"""add company_logo to employers

Revision ID: dd5de4337320
Revises: 7cf648ffe9b3
Create Date: 2025-09-28 00:08:54.835151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd5de4337320'
down_revision: Union[str, Sequence[str], None] = '7cf648ffe9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_application_job_candidate', 'applications', ['job_id', 'candidate_id'])
    op.add_column('employers', sa.Column('company_logo', sa.String(length=255), nullable=True))
    op.drop_index('ix_jobs_location', table_name='jobs')
    op.drop_index('ix_jobs_status', table_name='jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_location', 'jobs', ['location'], unique=False)
    op.drop_column('employers', 'company_logo')
    op.drop_constraint('uq_application_job_candidate', 'applications', type_='unique')
    # ### end Alembic commands ###
