"""add country, tel, img_path to candidates

Revision ID: f323d1cc54c1
Revises: af7a9d0ef9f1
Create Date: 2025-09-24 21:59:59.666544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f323d1cc54c1'
down_revision: Union[str, Sequence[str], None] = 'af7a9d0ef9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('tel', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('img_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'img_path')
    op.drop_column('candidates', 'tel')
    op.drop_column('candidates', 'country')
    # ### end Alembic commands ###
